name: cyber_safety
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_launcher_icons: ^0.14.4
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/spam_numbers_clean.json

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/cyber_safety.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
#  web:
#    generate: true
#    image_path: "path/to/image.png"
#    background_color: "#hexcode"
#    theme_color: "#hexcode"
#  windows:
#    generate: true
#    image_path: "path/to/image.png"
#    icon_size: 48 # min:48, max:256, default: 48
